title: CANFAR
tagline: Processing and Storage on the cloud
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
markdown: kramdown
highlighter: rouge
site_env: prod
env:
    demo:
        cadc: 'http://demo.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
    rc:
        cadc: 'http://rc.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
    prod:
        cadc: 'http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
    docker:
        cadc: 'http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
baseurl: ''
future: true
github_url: 'https://github.com/canfar/canfar.github.io'
twitter_url: 'https://twitter.com/astro_canfar'
slack_url: '/slack'
repository: 'canfar/canfar.github.io'
exclude:
    - node_modules
    - vendor
